{% set name = "tclreadline" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/flightaware/tclreadline/archive/v{{ version }}.tar.gz
  sha256: 306f9a72ef3ad9ff7a8549f1c616edef5365b98bce7e62fdde6e595355c0faee

build:
  number: 0
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make
  host:
    - tk
    - readline
  run:
    - tk
    - readline

test:
  commands:
    - test -f ${PREFIX}/include/tclreadline.h


about:
  home: https://github.com/flightaware/tclreadline
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: 'GNU readline for interactive tcl shells'
  doc_url: http://tclreadline.sourceforge.net/

extra:
  recipe-maintainers:
    - abretaud
